//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReservaCitasAfiliado.WSMedico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Medico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMaterno {
            get {
                return this.AMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AMaternoField, value) != true)) {
                    this.AMaternoField = value;
                    this.RaisePropertyChanged("AMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APaterno {
            get {
                return this.APaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.APaternoField, value) != true)) {
                    this.APaternoField = value;
                    this.RaisePropertyChanged("APaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedico {
            get {
                return this.IdMedicoField;
            }
            set {
                if ((this.IdMedicoField.Equals(value) != true)) {
                    this.IdMedicoField = value;
                    this.RaisePropertyChanged("IdMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSMedico.IMedicoService")]
    public interface IMedicoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/CrearMedico", ReplyAction="http://tempuri.org/IMedicoService/CrearMedicoResponse")]
        WebReservaCitasAfiliado.WSMedico.Medico CrearMedico(int idMedico, string nombre, string apaterno, string amaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/CrearMedico", ReplyAction="http://tempuri.org/IMedicoService/CrearMedicoResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> CrearMedicoAsync(int idMedico, string nombre, string apaterno, string amaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ObtenerMedico", ReplyAction="http://tempuri.org/IMedicoService/ObtenerMedicoResponse")]
        WebReservaCitasAfiliado.WSMedico.Medico ObtenerMedico(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ObtenerMedico", ReplyAction="http://tempuri.org/IMedicoService/ObtenerMedicoResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> ObtenerMedicoAsync(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ModificarMedico", ReplyAction="http://tempuri.org/IMedicoService/ModificarMedicoResponse")]
        WebReservaCitasAfiliado.WSMedico.Medico ModificarMedico(int idMedico, string nombre, string apaterno, string amaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ModificarMedico", ReplyAction="http://tempuri.org/IMedicoService/ModificarMedicoResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> ModificarMedicoAsync(int idMedico, string nombre, string apaterno, string amaterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/EliminarMedico", ReplyAction="http://tempuri.org/IMedicoService/EliminarMedicoResponse")]
        void EliminarMedico(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/EliminarMedico", ReplyAction="http://tempuri.org/IMedicoService/EliminarMedicoResponse")]
        System.Threading.Tasks.Task EliminarMedicoAsync(int idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ListarMedicos", ReplyAction="http://tempuri.org/IMedicoService/ListarMedicosResponse")]
        WebReservaCitasAfiliado.WSMedico.Medico[] ListarMedicos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicoService/ListarMedicos", ReplyAction="http://tempuri.org/IMedicoService/ListarMedicosResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico[]> ListarMedicosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMedicoServiceChannel : WebReservaCitasAfiliado.WSMedico.IMedicoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedicoServiceClient : System.ServiceModel.ClientBase<WebReservaCitasAfiliado.WSMedico.IMedicoService>, WebReservaCitasAfiliado.WSMedico.IMedicoService {
        
        public MedicoServiceClient() {
        }
        
        public MedicoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedicoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebReservaCitasAfiliado.WSMedico.Medico CrearMedico(int idMedico, string nombre, string apaterno, string amaterno) {
            return base.Channel.CrearMedico(idMedico, nombre, apaterno, amaterno);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> CrearMedicoAsync(int idMedico, string nombre, string apaterno, string amaterno) {
            return base.Channel.CrearMedicoAsync(idMedico, nombre, apaterno, amaterno);
        }
        
        public WebReservaCitasAfiliado.WSMedico.Medico ObtenerMedico(int idMedico) {
            return base.Channel.ObtenerMedico(idMedico);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> ObtenerMedicoAsync(int idMedico) {
            return base.Channel.ObtenerMedicoAsync(idMedico);
        }
        
        public WebReservaCitasAfiliado.WSMedico.Medico ModificarMedico(int idMedico, string nombre, string apaterno, string amaterno) {
            return base.Channel.ModificarMedico(idMedico, nombre, apaterno, amaterno);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico> ModificarMedicoAsync(int idMedico, string nombre, string apaterno, string amaterno) {
            return base.Channel.ModificarMedicoAsync(idMedico, nombre, apaterno, amaterno);
        }
        
        public void EliminarMedico(int idMedico) {
            base.Channel.EliminarMedico(idMedico);
        }
        
        public System.Threading.Tasks.Task EliminarMedicoAsync(int idMedico) {
            return base.Channel.EliminarMedicoAsync(idMedico);
        }
        
        public WebReservaCitasAfiliado.WSMedico.Medico[] ListarMedicos() {
            return base.Channel.ListarMedicos();
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSMedico.Medico[]> ListarMedicosAsync() {
            return base.Channel.ListarMedicosAsync();
        }
    }
}
