//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReservaCitasAfiliado.WSCentro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Centro", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Centro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAtencionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAtencion {
            get {
                return this.IdCentroAtencionField;
            }
            set {
                if ((this.IdCentroAtencionField.Equals(value) != true)) {
                    this.IdCentroAtencionField = value;
                    this.RaisePropertyChanged("IdCentroAtencion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCentro.ICentroService")]
    public interface ICentroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/CrearCentro", ReplyAction="http://tempuri.org/ICentroService/CrearCentroResponse")]
        WebReservaCitasAfiliado.WSCentro.Centro CrearCentro(int idCentro, string descripcion, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/CrearCentro", ReplyAction="http://tempuri.org/ICentroService/CrearCentroResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> CrearCentroAsync(int idCentro, string descripcion, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ObtenerCentro", ReplyAction="http://tempuri.org/ICentroService/ObtenerCentroResponse")]
        WebReservaCitasAfiliado.WSCentro.Centro ObtenerCentro(int idCentro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ObtenerCentro", ReplyAction="http://tempuri.org/ICentroService/ObtenerCentroResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> ObtenerCentroAsync(int idCentro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ModificarCentro", ReplyAction="http://tempuri.org/ICentroService/ModificarCentroResponse")]
        WebReservaCitasAfiliado.WSCentro.Centro ModificarCentro(int idCentro, string descripcion, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ModificarCentro", ReplyAction="http://tempuri.org/ICentroService/ModificarCentroResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> ModificarCentroAsync(int idCentro, string descripcion, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/EliminarCentro", ReplyAction="http://tempuri.org/ICentroService/EliminarCentroResponse")]
        void EliminarCentro(int idCentro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/EliminarCentro", ReplyAction="http://tempuri.org/ICentroService/EliminarCentroResponse")]
        System.Threading.Tasks.Task EliminarCentroAsync(int idCentro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ListarCentros", ReplyAction="http://tempuri.org/ICentroService/ListarCentrosResponse")]
        WebReservaCitasAfiliado.WSCentro.Centro[] ListarCentros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroService/ListarCentros", ReplyAction="http://tempuri.org/ICentroService/ListarCentrosResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro[]> ListarCentrosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentroServiceChannel : WebReservaCitasAfiliado.WSCentro.ICentroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentroServiceClient : System.ServiceModel.ClientBase<WebReservaCitasAfiliado.WSCentro.ICentroService>, WebReservaCitasAfiliado.WSCentro.ICentroService {
        
        public CentroServiceClient() {
        }
        
        public CentroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebReservaCitasAfiliado.WSCentro.Centro CrearCentro(int idCentro, string descripcion, string direccion) {
            return base.Channel.CrearCentro(idCentro, descripcion, direccion);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> CrearCentroAsync(int idCentro, string descripcion, string direccion) {
            return base.Channel.CrearCentroAsync(idCentro, descripcion, direccion);
        }
        
        public WebReservaCitasAfiliado.WSCentro.Centro ObtenerCentro(int idCentro) {
            return base.Channel.ObtenerCentro(idCentro);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> ObtenerCentroAsync(int idCentro) {
            return base.Channel.ObtenerCentroAsync(idCentro);
        }
        
        public WebReservaCitasAfiliado.WSCentro.Centro ModificarCentro(int idCentro, string descripcion, string direccion) {
            return base.Channel.ModificarCentro(idCentro, descripcion, direccion);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro> ModificarCentroAsync(int idCentro, string descripcion, string direccion) {
            return base.Channel.ModificarCentroAsync(idCentro, descripcion, direccion);
        }
        
        public void EliminarCentro(int idCentro) {
            base.Channel.EliminarCentro(idCentro);
        }
        
        public System.Threading.Tasks.Task EliminarCentroAsync(int idCentro) {
            return base.Channel.EliminarCentroAsync(idCentro);
        }
        
        public WebReservaCitasAfiliado.WSCentro.Centro[] ListarCentros() {
            return base.Channel.ListarCentros();
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSCentro.Centro[]> ListarCentrosAsync() {
            return base.Channel.ListarCentrosAsync();
        }
    }
}
