//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.WSReserva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaCita", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReservaCita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAsignadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAfiliadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdConsultorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReservaCitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAsignada {
            get {
                return this.FechaAsignadaField;
            }
            set {
                if ((this.FechaAsignadaField.Equals(value) != true)) {
                    this.FechaAsignadaField = value;
                    this.RaisePropertyChanged("FechaAsignada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAfiliado {
            get {
                return this.IdAfiliadoField;
            }
            set {
                if ((this.IdAfiliadoField.Equals(value) != true)) {
                    this.IdAfiliadoField = value;
                    this.RaisePropertyChanged("IdAfiliado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAtencion {
            get {
                return this.IdCentroAtencionField;
            }
            set {
                if ((this.IdCentroAtencionField.Equals(value) != true)) {
                    this.IdCentroAtencionField = value;
                    this.RaisePropertyChanged("IdCentroAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdConsultorio {
            get {
                return this.IdConsultorioField;
            }
            set {
                if ((this.IdConsultorioField.Equals(value) != true)) {
                    this.IdConsultorioField = value;
                    this.RaisePropertyChanged("IdConsultorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedico {
            get {
                return this.IdMedicoField;
            }
            set {
                if ((this.IdMedicoField.Equals(value) != true)) {
                    this.IdMedicoField = value;
                    this.RaisePropertyChanged("IdMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReservaCita {
            get {
                return this.IdReservaCitaField;
            }
            set {
                if ((this.IdReservaCitaField.Equals(value) != true)) {
                    this.IdReservaCitaField = value;
                    this.RaisePropertyChanged("IdReservaCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSReserva.IReservaCitaService")]
    public interface IReservaCitaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/CrearReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/CrearReservaCitaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/IReservaCitaService/CrearReservaCitaStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        RESTServices.WSReserva.ReservaCita CrearReservaCita(string dni, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/CrearReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/CrearReservaCitaResponse")]
        System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> CrearReservaCitaAsync(string dni, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ObtenerReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ObtenerReservaCitaResponse")]
        RESTServices.WSReserva.ReservaCita ObtenerReservaCita(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ObtenerReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ObtenerReservaCitaResponse")]
        System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> ObtenerReservaCitaAsync(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ModificarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ModificarReservaCitaResponse")]
        RESTServices.WSReserva.ReservaCita ModificarReservaCita(int idReserva, int idAfiliado, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ModificarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ModificarReservaCitaResponse")]
        System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> ModificarReservaCitaAsync(int idReserva, int idAfiliado, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/EliminarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/EliminarReservaCitaResponse")]
        void EliminarReservaCita(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/EliminarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/EliminarReservaCitaResponse")]
        System.Threading.Tasks.Task EliminarReservaCitaAsync(int idReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ListarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ListarReservaCitaResponse")]
        RESTServices.WSReserva.ReservaCita[] ListarReservaCita();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaCitaService/ListarReservaCita", ReplyAction="http://tempuri.org/IReservaCitaService/ListarReservaCitaResponse")]
        System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita[]> ListarReservaCitaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaCitaServiceChannel : RESTServices.WSReserva.IReservaCitaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaCitaServiceClient : System.ServiceModel.ClientBase<RESTServices.WSReserva.IReservaCitaService>, RESTServices.WSReserva.IReservaCitaService {
        
        public ReservaCitaServiceClient() {
        }
        
        public ReservaCitaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaCitaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaCitaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaCitaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RESTServices.WSReserva.ReservaCita CrearReservaCita(string dni, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado) {
            return base.Channel.CrearReservaCita(dni, idCentro, idMedico, idConsultorio, fechaAsignacion, observacion, estado);
        }
        
        public System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> CrearReservaCitaAsync(string dni, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado) {
            return base.Channel.CrearReservaCitaAsync(dni, idCentro, idMedico, idConsultorio, fechaAsignacion, observacion, estado);
        }
        
        public RESTServices.WSReserva.ReservaCita ObtenerReservaCita(int idReserva) {
            return base.Channel.ObtenerReservaCita(idReserva);
        }
        
        public System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> ObtenerReservaCitaAsync(int idReserva) {
            return base.Channel.ObtenerReservaCitaAsync(idReserva);
        }
        
        public RESTServices.WSReserva.ReservaCita ModificarReservaCita(int idReserva, int idAfiliado, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado) {
            return base.Channel.ModificarReservaCita(idReserva, idAfiliado, idCentro, idMedico, idConsultorio, fechaAsignacion, observacion, estado);
        }
        
        public System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita> ModificarReservaCitaAsync(int idReserva, int idAfiliado, int idCentro, int idMedico, int idConsultorio, System.DateTime fechaAsignacion, string observacion, int estado) {
            return base.Channel.ModificarReservaCitaAsync(idReserva, idAfiliado, idCentro, idMedico, idConsultorio, fechaAsignacion, observacion, estado);
        }
        
        public void EliminarReservaCita(int idReserva) {
            base.Channel.EliminarReservaCita(idReserva);
        }
        
        public System.Threading.Tasks.Task EliminarReservaCitaAsync(int idReserva) {
            return base.Channel.EliminarReservaCitaAsync(idReserva);
        }
        
        public RESTServices.WSReserva.ReservaCita[] ListarReservaCita() {
            return base.Channel.ListarReservaCita();
        }
        
        public System.Threading.Tasks.Task<RESTServices.WSReserva.ReservaCita[]> ListarReservaCitaAsync() {
            return base.Channel.ListarReservaCitaAsync();
        }
    }
}
