//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReservaCitasAfiliado.WSConsultorio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consultorio", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Consultorio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdConsultorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroConsultorioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAtencion {
            get {
                return this.IdCentroAtencionField;
            }
            set {
                if ((this.IdCentroAtencionField.Equals(value) != true)) {
                    this.IdCentroAtencionField = value;
                    this.RaisePropertyChanged("IdCentroAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdConsultorio {
            get {
                return this.IdConsultorioField;
            }
            set {
                if ((this.IdConsultorioField.Equals(value) != true)) {
                    this.IdConsultorioField = value;
                    this.RaisePropertyChanged("IdConsultorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroConsultorio {
            get {
                return this.NroConsultorioField;
            }
            set {
                if ((object.ReferenceEquals(this.NroConsultorioField, value) != true)) {
                    this.NroConsultorioField = value;
                    this.RaisePropertyChanged("NroConsultorio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSConsultorio.IConsultorioService")]
    public interface IConsultorioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/CrearConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/CrearConsultorioResponse")]
        WebReservaCitasAfiliado.WSConsultorio.Consultorio CrearConsultorio(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/CrearConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/CrearConsultorioResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> CrearConsultorioAsync(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ObtenerConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/ObtenerConsultorioResponse")]
        WebReservaCitasAfiliado.WSConsultorio.Consultorio ObtenerConsultorio(int idConsultorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ObtenerConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/ObtenerConsultorioResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> ObtenerConsultorioAsync(int idConsultorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ModificarConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/ModificarConsultorioResponse")]
        WebReservaCitasAfiliado.WSConsultorio.Consultorio ModificarConsultorio(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ModificarConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/ModificarConsultorioResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> ModificarConsultorioAsync(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/EliminarConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/EliminarConsultorioResponse")]
        void EliminarConsultorio(int idConsultorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/EliminarConsultorio", ReplyAction="http://tempuri.org/IConsultorioService/EliminarConsultorioResponse")]
        System.Threading.Tasks.Task EliminarConsultorioAsync(int idConsultorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ListarConsultorios", ReplyAction="http://tempuri.org/IConsultorioService/ListarConsultoriosResponse")]
        WebReservaCitasAfiliado.WSConsultorio.Consultorio[] ListarConsultorios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ListarConsultorios", ReplyAction="http://tempuri.org/IConsultorioService/ListarConsultoriosResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio[]> ListarConsultoriosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ListarPorCentro", ReplyAction="http://tempuri.org/IConsultorioService/ListarPorCentroResponse")]
        WebReservaCitasAfiliado.WSConsultorio.Consultorio[] ListarPorCentro(int idCentro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultorioService/ListarPorCentro", ReplyAction="http://tempuri.org/IConsultorioService/ListarPorCentroResponse")]
        System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio[]> ListarPorCentroAsync(int idCentro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultorioServiceChannel : WebReservaCitasAfiliado.WSConsultorio.IConsultorioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultorioServiceClient : System.ServiceModel.ClientBase<WebReservaCitasAfiliado.WSConsultorio.IConsultorioService>, WebReservaCitasAfiliado.WSConsultorio.IConsultorioService {
        
        public ConsultorioServiceClient() {
        }
        
        public ConsultorioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultorioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultorioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultorioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebReservaCitasAfiliado.WSConsultorio.Consultorio CrearConsultorio(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado) {
            return base.Channel.CrearConsultorio(idConsultorio, idCentro, nroConsultorio, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> CrearConsultorioAsync(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado) {
            return base.Channel.CrearConsultorioAsync(idConsultorio, idCentro, nroConsultorio, descripcion, estado);
        }
        
        public WebReservaCitasAfiliado.WSConsultorio.Consultorio ObtenerConsultorio(int idConsultorio) {
            return base.Channel.ObtenerConsultorio(idConsultorio);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> ObtenerConsultorioAsync(int idConsultorio) {
            return base.Channel.ObtenerConsultorioAsync(idConsultorio);
        }
        
        public WebReservaCitasAfiliado.WSConsultorio.Consultorio ModificarConsultorio(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado) {
            return base.Channel.ModificarConsultorio(idConsultorio, idCentro, nroConsultorio, descripcion, estado);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio> ModificarConsultorioAsync(int idConsultorio, int idCentro, string nroConsultorio, string descripcion, int estado) {
            return base.Channel.ModificarConsultorioAsync(idConsultorio, idCentro, nroConsultorio, descripcion, estado);
        }
        
        public void EliminarConsultorio(int idConsultorio) {
            base.Channel.EliminarConsultorio(idConsultorio);
        }
        
        public System.Threading.Tasks.Task EliminarConsultorioAsync(int idConsultorio) {
            return base.Channel.EliminarConsultorioAsync(idConsultorio);
        }
        
        public WebReservaCitasAfiliado.WSConsultorio.Consultorio[] ListarConsultorios() {
            return base.Channel.ListarConsultorios();
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio[]> ListarConsultoriosAsync() {
            return base.Channel.ListarConsultoriosAsync();
        }
        
        public WebReservaCitasAfiliado.WSConsultorio.Consultorio[] ListarPorCentro(int idCentro) {
            return base.Channel.ListarPorCentro(idCentro);
        }
        
        public System.Threading.Tasks.Task<WebReservaCitasAfiliado.WSConsultorio.Consultorio[]> ListarPorCentroAsync(int idCentro) {
            return base.Channel.ListarPorCentroAsync(idCentro);
        }
    }
}
